# Generated by Django 2.0.4 on 2018-04-27 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0003_auto_20180427_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Category')),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.RemoveField(
            model_name='articale',
            name='article_author',
        ),
        migrations.RemoveField(
            model_name='articale',
            name='category',
        ),
        migrations.DeleteModel(
            name='articale',
        ),
    ]
