# Generated by Django 2.0.4 on 2018-04-27 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20180427_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='post_time',
            new_name='posted_on',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='update_time',
            new_name='update_on',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Category'),
        ),
    ]
