# Generated by Django 2.0.4 on 2018-04-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20180427_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
