# Generated by Django 2.0.4 on 2018-04-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0033_auto_20180429_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Category'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
